name: 'Danger action'
description: 'Run danger'
author: 'MeilCli'
branding:
  icon: zap
  color: red
inputs:
  danger_version:
    description: 'danger version'
    default: '>= 6.0.0'
  plugins_file:
    description: 'gemfile for danger plugin. if set plugins_file, action do not exec gem install'
  install_path:
    description: 'bundle install path'
  danger_file:
    description: 'dangerfile for danger'
    required: true
  danger_id:
    description: 'danger id, set identifier string'
    required: true
runs:
  using: 'node12'
  main: 'dist/main.js'
