name: 'Danger action'
description: 'run danger'
author: 'MeilCli'
inputs:
  danger_version:
    description: 'danger version'
    default: '~> 6.0'
  plugins_file:
    description: 'gemfile for danger plugin'
  danger_file:
    description: 'dangerfile for danger'
    required: true
  danger_id:
    description: 'danger id, set identifier string'
    required: true
runs:
  using: 'node12'
  main: 'lib/main.js'