name: 'Danger action'
description: 'Run danger'
author: 'MeilCli'
branding:
  icon: zap
  color: red
inputs:
  danger_version:
    description: 'danger version'
    default: '>= 6.0.0'
  danger_version_file:
    description: 'danger version file'
    default: '.tool-versions'
  danger_version_file_format:
    description: 'danger version file format'
    default: 'asdf'
  plugins_file:
    description: 'gemfile for danger plugin. if set plugins_file, action do not exec gem install'
  install_path:
    description: 'bundle install path'
  danger_file:
    description: 'dangerfile for danger'
    required: true
  danger_id:
    description: 'danger id, set identifier string'
    required: true
  fail_on_stderr_when_bundler:
    description: 'action fail when bunder output stderr'
    default: 'false'
  fail_on_stderr_when_danger:
    description: 'action fail when danger output stderr'
    default: 'false'
runs:
  using: 'node20'
  main: 'dist/index.js'
