on:
  workflow_call:

jobs:
  danger:
    runs-on: ubuntu-latest
    if: github.event_name  == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: npm install
        run: npm install
        env:
          CI: true
      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-danger-gems-${{ hashFiles('Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-danger-gems-
      - name: Bundle config
        run: bundle config path vendor/bundle
      - uses: ./
        with:
          plugins_file: 'Gemfile'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
