name: CI-PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/ci-base-build.yml
    secrets: inherit
  danger:
    uses: ./.github/workflows/ci-base-danger.yml
    secrets: inherit
  approve:
    uses: ./.github/workflows/ci-base-approve.yml
    secrets: inherit
    needs: build
  merge:
    uses: ./.github/workflows/ci-base-merge.yml
    secrets: inherit
    needs: build
