name: Metrics
on:
  push: { branches: ['master', 'main'] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics_contributors.svg
          repo: danger-action
          template: repository
          base: ''
          output_action: gist
          committer_gist: ${{ secrets.METRICS_GIST }}
          plugin_contributors: yes
          plugin_contributors_sections: contributors,categories
          plugin_contributors_categories: |
            {
              "📚 Documentation":["**/*.md"],
              "💻 Code":["**/*.ts"]
            }

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics_licenses.svg
          repo: danger-action
          template: repository
          base: ''
          output_action: gist
          committer_gist: ${{ secrets.METRICS_GIST }}
          plugin_licenses: yes
          plugin_licenses_setup: npm ci
          plugin_licenses_ratio: yes
          plugin_licenses_legal: yes
